# Generated by Django 4.2.4 on 2023-08-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_tag_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
    ]
